import type { ChecklistCategory } from "../../title-checklist";

export const LOOM_CHECKLIST_CATEGORIES: ChecklistCategory[] = [
  {
    id: "loom-bunny",
    kind: "community",
    title: "Personalized Bunny Baby Blanket",
    items: [
      "Floral bunny",
      "Garden bunny",
      "Sleepy bunny",
      "Bunny with bow",
      "Spring bunny",
      "Woodland bunny",
      "Pastel bunny",
      "Bunny and stars",
      "Bunny and hearts",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["bunny blanket", "bunny gift"],
      support: ["Baby Shower Gift", "Custom Name Blanket"],
    },
  },
  {
    id: "loom-bear",
    kind: "community",
    title: "Personalized Bear Baby Blanket",
    items: [
      "Teddy bear",
      "Woodland bear",
      "Sleepy bear",
      "Bear and moon",
      "Floral bear",
      "Bear hug",
      "Bear and stars",
      "Bear and hearts",
      "Neutral bear",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["bear blanket", "teddy gift"],
      support: ["New Baby Gift", "Nursery Decor"],
    },
  },
  {
    id: "loom-elephant",
    kind: "community",
    title: "Personalized Elephant Baby Blanket",
    items: [
      "Floral elephant",
      "Safari elephant",
      "Sleepy elephant",
      "Elephant and stars",
      "Elephant and hearts",
      "Watercolor elephant",
      "Neutral elephant",
      "Elephant and moon",
      "Elephant family",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["elephant blanket", "safari gift"],
      support: ["Baby Girl Gift", "Baby Boy Gift"],
    },
  },
  {
    id: "loom-deer",
    kind: "targeted",
    title: "Personalized Deer Baby Blanket",
    items: [
      "Woodland deer",
      "Floral deer",
      "Fawn and flowers",
      "Deer and stars",
      "Deer and hearts",
      "Forest deer",
      "Neutral deer",
      "Deer family",
      "Deer and moon",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["deer blanket", "woodland gift"],
      support: ["Nursery Decor", "Newborn Gift"],
    },
  },
  {
    id: "loom-fox",
    kind: "targeted",
    title: "Personalized Fox Baby Blanket",
    items: [
      "Woodland fox",
      "Floral fox",
      "Sleepy fox",
      "Fox and stars",
      "Fox and hearts",
      "Forest fox",
      "Neutral fox",
      "Fox family",
      "Fox and moon",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["fox blanket", "woodland gift"],
      support: ["Baby Shower Gift", "Custom Name Blanket"],
    },
  },
  {
    id: "loom-highland-cow",
    kind: "targeted",
    title: "Personalized Highland Cow Baby Blanket",
    items: [
      "Highland cow",
      "Floral highland cow",
      "Farm highland cow",
      "Highland cow and stars",
      "Highland cow and hearts",
      "Neutral highland cow",
      "Highland cow family",
      "Pastel highland cow",
      "Highland cow and moon",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["highland cow", "farm nursery"],
      support: ["New Baby Gift", "Personalized Gift"],
    },
  },
  {
    id: "loom-woodland",
    kind: "targeted",
    title: "Personalized Woodland Baby Blanket",
    items: [
      "Woodland animals",
      "Forest friends",
      "Woodland wreath",
      "Woodland trees",
      "Woodland leaves",
      "Woodland mushrooms",
      "Woodland stars",
      "Woodland moon",
      "Woodland floral",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["woodland blanket", "nursery decor"],
      support: ["Baby Shower Gift", "Newborn Gift"],
    },
  },
  {
    id: "loom-safari",
    kind: "targeted",
    title: "Personalized Safari Baby Blanket",
    items: [
      "Safari animals",
      "Giraffe",
      "Lion",
      "Zebra",
      "Elephant safari",
      "Safari jeep",
      "Safari trees",
      "Safari stars",
      "Safari floral",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["safari blanket", "safari nursery"],
      support: ["Baby Boy Gift", "Baby Girl Gift"],
    },
  },
  {
    id: "loom-rainbow",
    kind: "targeted",
    title: "Personalized Boho Rainbow Baby Blanket",
    items: [
      "Boho rainbow",
      "Pastel rainbow",
      "Rainbow and clouds",
      "Rainbow and stars",
      "Rainbow arches",
      "Neutral rainbow",
      "Rainbow floral",
      "Rainbow moon",
      "Rainbow hearts",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["rainbow blanket", "boho nursery"],
      support: ["Nursery Decor", "Baby Shower Gift"],
    },
  },
  {
    id: "loom-moon-stars",
    kind: "targeted",
    title: "Personalized Moon and Stars Baby Blanket",
    items: [
      "Moon and stars",
      "Sleepy moon",
      "Celestial moon",
      "Stars and clouds",
      "Night sky",
      "Moon and hearts",
      "Neutral moon",
      "Pastel moon",
      "Moon and floral",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["moon blanket", "celestial gift"],
      support: ["New Baby Gift", "Custom Name Blanket"],
    },
  },
  {
    id: "loom-floral",
    kind: "targeted",
    title: "Personalized Floral Baby Blanket",
    items: [
      "Wildflower",
      "Peony floral",
      "Daisy floral",
      "Rose floral",
      "Botanical floral",
      "Pastel floral",
      "Neutral floral",
      "Floral wreath",
      "Floral name",
    ],
    seoBrief: {
      lead: "Personalized Baby Blanket",
      niche: ["floral blanket", "floral nursery"],
      support: ["Baby Girl Gift", "Personalized Gift"],
    },
  },
];

export function getLoomSeoBriefForSubject(subject: string) {
  const needle = subject.trim().toLowerCase();
  if (!needle) return null;
  const match = LOOM_CHECKLIST_CATEGORIES.find(
    (c) => c.title.toLowerCase() === needle
  );
  return match?.seoBrief ?? null;
}
